version: 2
updates:
  # NPM Dependencies - Core Production Dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    target-branch: "main"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "production"
    reviewers:
      - "hadyfayed"
    assignees:
      - "hadyfayed"
    labels:
      - "dependencies"
      - "npm"
      - "production"
    commit-message:
      prefix: "npm"
      include: "scope"
    groups:
      react-ecosystem:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      typescript-ecosystem:
        patterns:
          - "typescript"
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      build-tools:
        patterns:
          - "vite*"
          - "@vitejs/*"
          - "rollup*"
          - "@rollup/*"
        update-types:
          - "minor"
          - "patch"

  # NPM Dependencies - Development Dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
    target-branch: "main"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "development"
    reviewers:
      - "hadyfayed"
    assignees:
      - "hadyfayed"
    labels:
      - "dependencies"
      - "npm"
      - "development"
    commit-message:
      prefix: "npm(dev)"
      include: "scope"
    groups:
      testing-tools:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "@testing-library/*"
          - "jsdom"
        update-types:
          - "minor"
          - "patch"
      linting-tools:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "@typescript-eslint/*"
          - "prettier"
        update-types:
          - "minor"
          - "patch"
      babel-tools:
        patterns:
          - "@babel/*"
        update-types:
          - "minor"
          - "patch"

  # Composer Dependencies - Production
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
    target-branch: "main"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "production"
    reviewers:
      - "hadyfayed"
    assignees:
      - "hadyfayed"
    labels:
      - "dependencies"
      - "composer"
      - "production"
    commit-message:
      prefix: "composer"
      include: "scope"
    groups:
      laravel-ecosystem:
        patterns:
          - "laravel/*"
          - "illuminate/*"
        update-types:
          - "minor"
          - "patch"
      filament-ecosystem:
        patterns:
          - "filament/*"
        update-types:
          - "minor"
          - "patch"
      livewire-ecosystem:
        patterns:
          - "livewire/*"
        update-types:
          - "minor"
          - "patch"

  # Composer Dependencies - Development
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "04:00"
    target-branch: "main"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "development"
    reviewers:
      - "hadyfayed"
    assignees:
      - "hadyfayed"
    labels:
      - "dependencies"
      - "composer"
      - "development"
    commit-message:
      prefix: "composer(dev)"
      include: "scope"
    groups:
      testing-tools:
        patterns:
          - "phpunit/*"
          - "orchestra/*"
          - "mockery/*"
        update-types:
          - "minor"
          - "patch"

  # Security Updates - High Priority
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    reviewers:
      - "hadyfayed"
    assignees:
      - "hadyfayed"
    labels:
      - "security"
      - "critical"
      - "npm"
    commit-message:
      prefix: "security(npm)"
      include: "scope"
    # Only security updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    reviewers:
      - "hadyfayed"
    assignees:
      - "hadyfayed"
    labels:
      - "security"
      - "critical"
      - "composer"
    commit-message:
      prefix: "security(composer)"
      include: "scope"
    # Only security updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]