name: Basic Test

on:
  push:
    branches: [ main ]

jobs:
  basic-check:
    name: Basic Environment Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check files
        run: |
          echo "Current directory:"
          pwd
          echo "Files in directory:"
          ls -la
          echo "Package.json exists:"
          ls -la package.json
          echo "Node version available:"
          node --version
          echo "NPM version available:"
          npm --version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Check npm setup
        run: |
          echo "After Node setup:"
          node --version
          npm --version
          echo "Package.json content:"
          cat package.json | head -20

      - name: Install dependencies
        run: npm ci

      - name: Check installation
        run: |
          echo "Dependencies installed:"
          npm list --depth=0 | head -10